[package]
name = "plugins"
version = "0.1.0"
edition = "2021"

[features]
default = []
stub-plugins = []
real-plugins = ["dep:chromiumoxide", "dep:tokio", "dep:futures"]

[dependencies]
domain = { path = "../domain" }
serde = { version = "1", features = ["derive"] }
toml = "0.6"
regex = "1"
chromiumoxide = { version = "0.9", optional = true, features = ["rustls", "zip8"] }
futures = { version = "0.3", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
