[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
utoipa = { version = "4", features = ["uuid", "chrono"] }
uuid = { version = "=1.8.0", default-features = false, features = ["serde", "v4"] }

[dev-dependencies]
futures = "0.3"
serde_json = "1"
